test

diff --git a/.azure-pipelines/ASIMSchemaDataTester.yaml b/.azure-pipelines/ASIMSchemaDataTester.yaml
--- a/.azure-pipelines/ASIMSchemaDataTester.yaml
+++ b/.azure-pipelines/ASIMSchemaDataTester.yaml
@@ -1,12 +1,31 @@
 jobs:
 - job: "ASIMSchemaDataTester"
+  displayName: 'Run ASIM testers on "eco-connector-test" workspace'
   pool:
     vmImage: 'ubuntu-latest'
   steps:
-  - script: 'npm install -g npm@6.14.15;which npm;npm -v'
-  - task: Npm@1
-    displayName: 'npm install'
+  - checkout: self
+    persistCredentials: false
+    fetchDepth: 0
+  - task: AzureCLI@2
     inputs:
-      verbose: false
-  - script: 'npm run tsc && node .script/yamlFileValidator.ts'
-    displayName: 'Yaml File Syntax Validation'
+      azureSubscription: '$(AZURE_SUBSCRIPTION_ID)'
+      scriptType: 'ps'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
+        az account set --subscription $(AZURE_SUBSCRIPTION_ID)
+      addSpnToEnvironment: true
+  - script: |
+      git config --local user.name "azure-pipelines[bot]"
+      git config --local user.email "<>"
+    displayName: 'Setup git config'
+  - script: |
+      git merge origin/master
+      Conflicts=$(git ls-files -u | wc -l)
+      if [ "$Conflicts" -gt 0 ] ; then
+        echo "There is a merge conflict. Aborting"
+        git merge --abort
+        exit 1
+      fi
+    displayName: 'Merge master into pull request branch'
