test

diff --git a/.azure-pipelines/ASIMSchemaDataTester.yaml b/.azure-pipelines/ASIMSchemaDataTester.yaml
--- a/.azure-pipelines/ASIMSchemaDataTester.yaml
+++ b/.azure-pipelines/ASIMSchemaDataTester.yaml
@@ -15,3 +15,17 @@ jobs:
       inlineScript: |
         set -e  # Exit on error
         echo "Running Azure CLI commands..."
+      addSpnToEnvironment: true  # Add SPN credentials to environment variables for use in subsequent steps
+  - script: |
+      git config --local user.name "azure-pipelines[bot]"
+      git config --local user.email "<>"
+    displayName: 'Setup git config'
+  - script: |
+      git merge origin/master
+      Conflicts=$(git ls-files -u | wc -l)
+      if [ "$Conflicts" -gt 0 ] ; then
+        echo "There is a merge conflict. Aborting"
+        git merge --abort
+        exit 1
+      fi
+    displayName: 'Merge master into pull request branch'
