test

diff --git a/.azure-pipelines/ASIMSchemaDataTester.yaml b/.azure-pipelines/ASIMSchemaDataTester.yaml
--- a/.azure-pipelines/ASIMSchemaDataTester.yaml
+++ b/.azure-pipelines/ASIMSchemaDataTester.yaml
@@ -26,17 +26,12 @@ jobs:
     persistCredentials: false
     fetchDepth: 0  # Fetch full repository history
 
-  - task: AzureCLI@2
-    inputs:
-      azureSubscription: 'ASIM-SchemaDataTester-ServiceConnection'  # Name of your Azure service connection
-      scriptType: 'bash'
-      scriptLocation: 'inlineScript'
-      inlineScript: |
-        set -e  # Exit on error
-        echo "Running Azure CLI commands..."
-        # Example command to list resource groups
-        az group list
-      addSpnToEnvironment: true  # Add SPN credentials to environment variables for use in subsequent steps
+  - script: |
+      set -e  # Exit on error
+      echo "Running Azure CLI commands..."
+      # Example command to list resource groups
+      az group list
+    displayName: 'Run Azure CLI commands'
 
   - script: |
       git config --local user.name "azure-pipelines[bot]"
