test

diff --git a/.azure-pipelines/ASIMSchemaDataTester.yaml b/.azure-pipelines/ASIMSchemaDataTester.yaml
--- a/.azure-pipelines/ASIMSchemaDataTester.yaml
+++ b/.azure-pipelines/ASIMSchemaDataTester.yaml
@@ -1,7 +1,6 @@
 jobs:
 - job: "ASIMSchemaDataTester"
   displayName: 'Run ASIM testers on "eco-connector-test" workspace'
-  
   pool:
     vmImage: 'ubuntu-latest'
 
@@ -13,21 +12,17 @@ jobs:
       sudo apt-get update
       sudo apt-get install -y jq
 
-      # Get the organization name and project name from environment variables
+      # Set variables
       ORG_NAME=$(System.CollectionUri)
       PROJECT_NAME=$(System.TeamProject)
-
-      # Get the repository ID and pull request ID from environment variables
-      REPO_ID=$(Build.Repository.ID)
+      REPO_ID=$(Build.Repository.Name)
       PR_ID=$(System.PullRequest.PullRequestId)
+      AZURE_DEVOPS_TOKEN=$(System.AccessToken)
 
-      echo "Organization: $ORG_NAME"
-      echo "Project: $PROJECT_NAME"
-      echo "Repository: $REPO_ID"
-      echo "Pull Request ID: $PR_ID"
-
-      # Fetch the list of changed files in the PR
-      changed_files=$(az repos pr list --id $PR_ID --repository-id $REPO_ID --org $ORG_NAME --project $PROJECT_NAME --query 'changes[].item.path' -o tsv)
+      # Get the list of changed files in the PR
+      changed_files=$(curl -s -u :$AZURE_DEVOPS_TOKEN \
+        "$ORG_NAME$PROJECT_NAME/_apis/git/repositories/$REPO_ID/pullRequests/$PR_ID/iterations/1/changes?api-version=6.0" | \
+        jq -r '.changes[].item.path')
 
       echo "Changed files: $changed_files"
 
@@ -46,3 +41,64 @@ jobs:
            [[ $file == Parsers/ASimRegistryEvent/Parsers/* ]] || \
            [[ $file == Parsers/ASimUserManagement/Parsers/* ]] || \
            [[ $file == Parsers/ASimDhcpEvent/Parsers/* ]]; then
+          echo "Found changed file $file in specified locations."
+          files_changed=true
+          break
+        fi
+      done
+
+      # Set the pipeline variable
+      echo "##vso[task.setvariable variable=filesChanged;isOutput=true]$files_changed"
+    displayName: 'Check for Changed Files in Specified Locations'
+
+  - script: |
+      echo "No relevant files changed."
+      exit 0
+    displayName: 'Skip job if no relevant files changed'
+    condition: and(succeeded(), eq(variables['filesChanged'], 'false'))
+
+  - checkout: self
+    persistCredentials: false
+    fetchDepth: 0  # Fetch full repository history
+    condition: and(succeeded(), eq(variables['filesChanged'], 'true'))
+
+  - task: AzureCLI@2
+    inputs:
+      azureSubscription: 'ASIM-SchemaDataTester-ServiceConnection'  # name of your Azure service connection
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e  # Exit on error
+        echo "Running Azure CLI commands..."
+        # Example command to list resource groups
+        az group list
+      addSpnToEnvironment: true  # Add SPN credentials to environment variables for use in subsequent steps
+    condition: and(succeeded(), eq(variables['filesChanged'], 'true'))
+
+  - script: |
+      git config --local user.name "azure-pipelines[bot]"
+      git config --local user.email "<>"
+    displayName: 'Setup git config'
+    condition: and(succeeded(), eq(variables['filesChanged'], 'true'))
+
+  - script: |
+      git merge origin/master
+      Conflicts=$(git ls-files -u | wc -l)
+      if [ "$Conflicts" -gt 0 ] ; then
+        echo "There is a merge conflict. Aborting"
+        git merge --abort
+        exit 1
+      fi
+    displayName: 'Merge master into pull request branch'
+    condition: and(succeeded(), eq(variables['filesChanged'], 'true'))
+
+  - task: AzurePowerShell@5
+    inputs:
+      azureSubscription: 'ASIM-SchemaDataTester-ServiceConnection'
+      ScriptType: 'InlineScript'
+      Inline: |
+        & ".script/tests/asimParsersTest/runAsimTesters.ps1"
+      FailOnStandardError: false
+      ErrorActionPreference: 'continue'
+      azurePowerShellVersion: 'latest'
+    condition: and(succeeded(), eq(variables['filesChanged'], 'true'))
