test

diff --git a/.azure-pipelines/ASIMSchemaDataTester.yaml b/.azure-pipelines/ASIMSchemaDataTester.yaml
--- a/.azure-pipelines/ASIMSchemaDataTester.yaml
+++ b/.azure-pipelines/ASIMSchemaDataTester.yaml
@@ -1,26 +1,27 @@
-pool:
-  vmImage: 'ubuntu-latest'
-  
 jobs:
-- job: ASIMSchemaDataTester
+- job: "ASIMSchemaDataTester"
   displayName: 'Run ASIM testers on "eco-connector-test" workspace'
+  pool:
+    vmImage: 'ubuntu-latest'
   steps:
   - checkout: self
     persistCredentials: false
     fetchDepth: 0  # Fetch full repository history
-
-  - script: |
-      set -e  # Exit on error
-      echo "Running Azure CLI commands..."
-      # Example command to list resource groups
-      az group list
-    displayName: 'Run Azure CLI commands'
-
+  - task: AzureCLI@2
+    inputs:
+      azureSubscription: 'ASIM-SchemaDataTester-ServiceConnection'  # name of your Azure service connection
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e  # Exit on error
+        echo "Running Azure CLI commands..."
+        # Example command to list resource groups
+        az group list
+      addSpnToEnvironment: true  # Add SPN credentials to environment variables for use in subsequent steps
   - script: |
       git config --local user.name "azure-pipelines[bot]"
       git config --local user.email "<>"
     displayName: 'Setup git config'
-
   - script: |
       git merge origin/master
       Conflicts=$(git ls-files -u | wc -l)
@@ -30,7 +31,6 @@ jobs:
         exit 1
       fi
     displayName: 'Merge master into pull request branch'
-
   - task: AzurePowerShell@5
     inputs:
       azureSubscription: 'ASIM-SchemaDataTester-ServiceConnection'
