Update runAsimSchemaAndDataTesters.yaml

diff --git a/.github/workflows/runAsimSchemaAndDataTesters.yaml b/.github/workflows/runAsimSchemaAndDataTesters.yaml
--- a/.github/workflows/runAsimSchemaAndDataTesters.yaml
+++ b/.github/workflows/runAsimSchemaAndDataTesters.yaml
@@ -8,7 +8,96 @@ permissions:
   contents: read
 
 jobs: 
+  Run-ASim-TemplateValidation:
+    name: Run ASim Template Validation tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout pull request branch
+        uses: actions/checkout@v3
+        with:
+            ref: ${{github.event.pull_request.head.ref}}
+            repository: ${{github.event.pull_request.head.repo.full_name}}
+            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
+            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
+      - name: Setup git config
+        run: |
+              git config --local user.name "github-actions[bot]"
+              git config --local user.email "<>"
+      - name: Merge master into pull request branch
+        run: |
+              git merge origin/master
+              Conflicts=$(git ls-files -u | wc -l)
+              if [ "$Conflicts" -gt 0 ] ; then
+                echo "There is a merge conflict. Aborting"
+                git merge --abort
+                exit 1
+              fi
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+      - name: Install dependencies
+        run: |
+              python -m pip install --upgrade pip
+              pip install requests
+              pip install PyYAML
+              pip install tabulate
+      - name: Run ASim parsers template validations python script
+        run: |
+              filePath=".script/tests/asimParsersTest/VerifyASimParserTemplate.py"
+              url="https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/.script/tests/asimParsersTest/VerifyASimParserTemplate.py" 
+              # Check if file exists and delete if it does
+              if [ -f "$filePath" ]; then
+                rm -f "$filePath"
+              fi
+              # Download the file
+              echo "Downloading script from the master: $url"
+              curl -o "$filePath" "$url"
+              # Execute the script
+              python "$filePath" 
+  Run-ASim-Sample-Data-Ingest:
+    needs: Run-ASim-TemplateValidation
+    name: Run ASim Sample Data Ingestion
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.x'
+      - name: Install dependencies
+        run: |
+              python -m pip install --upgrade pip
+              pip install azure-identity
+              pip install requests
+              pip install PyYAML
+              pip install azure-monitor-ingestion
+              pip install azure-core
+      - name: Login to Azure Public Cloud
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZURE_ASIM_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          allow-no-subscriptions: true
+      - name: Asim Sample Log Ingestion
+        id: Ingestlogs
+        run: |
+              filePath=".script/tests/asimParsersTest/ingestASimSampleData.py"
+              url="https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/.script/tests/asimParsersTest/ingestASimSampleData.py" 
+              # Check if file exists and delete if it does
+              if [ -f "$filePath" ]; then
+                rm -f "$filePath"
+              fi
+              # Download the file
+              echo "Downloading script from the master: $url"
+              curl -o "$filePath" "$url"
+              # Execute the script
+              python3 "$filePath" ${{ github.event.pull_request.number }}
   Run-ASim-Schema-Data-tests:
+    needs: Run-ASim-Sample-Data-Ingest
     name: Run ASim Schema and Data tests
     runs-on: ubuntu-latest
     steps:
@@ -60,54 +149,8 @@ jobs:
           azPSVersion: "latest"
           errorActionPreference: continue
           failOnStandardError: false
-  Run-ASim-TemplateValidation:
-    name: Run ASim Template Validation tests
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout pull request branch
-        uses: actions/checkout@v3
-        with:
-            ref: ${{github.event.pull_request.head.ref}}
-            repository: ${{github.event.pull_request.head.repo.full_name}}
-            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
-            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
-      - name: Setup git config
-        run: |
-              git config --local user.name "github-actions[bot]"
-              git config --local user.email "<>"
-      - name: Merge master into pull request branch
-        run: |
-              git merge origin/master
-              Conflicts=$(git ls-files -u | wc -l)
-              if [ "$Conflicts" -gt 0 ] ; then
-                echo "There is a merge conflict. Aborting"
-                git merge --abort
-                exit 1
-              fi
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.x'
-      - name: Install dependencies
-        run: |
-              python -m pip install --upgrade pip
-              pip install requests
-              pip install PyYAML
-              pip install tabulate
-      - name: Run ASim parsers template validations python script
-        run: |
-              filePath=".script/tests/asimParsersTest/VerifyASimParserTemplate.py"
-              url="https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/.script/tests/asimParsersTest/VerifyASimParserTemplate.py" 
-              # Check if file exists and delete if it does
-              if [ -f "$filePath" ]; then
-                rm -f "$filePath"
-              fi
-              # Download the file
-              echo "Downloading script from the master: $url"
-              curl -o "$filePath" "$url"
-              # Execute the script
-              python "$filePath"
   Run-ASim-Parser-Filtering-Tests:
+    needs: Run-ASim-Sample-Data-Ingest
     name: Run ASim Parser Filtering tests
     runs-on: ubuntu-latest
     steps:
@@ -159,34 +202,4 @@ jobs:
           echo "Downloading script from the master: $url"
           curl -o "$filePath" "$url"
           # Execute the script
-          python "$filePath"
-  Run-ASim-Sample-Data-Ingest:
-    name: Run ASim Sample Data Ingestion
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.x'
-      - name: Install dependencies
-        run: |
-              python -m pip install --upgrade pip
-              pip install azure-identity
-              pip install requests
-              pip install PyYAML
-              pip install azure-monitor-ingestion
-              pip install azure-core
-      - name: Login to Azure Public Cloud
-        uses: azure/login@v2
-        with:
-          client-id: ${{ secrets.AZURE_ASIM_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          allow-no-subscriptions: true
-      - name: Asim Sample Log Ingestion
-        id: Ingestlogs
-        run: |
-              python3 .script/tests/asimParsersTest/ingestAsimSampleData.py ${{ github.event.pull_request.number }}
+          python "$filePath"                                      
